config/routes.rb
Rails.application.routes.draw do

  get 'rel_booking/rel_book'

  resources :details
  resources :services


  get 'rel_customer/rel_cust'

  get 'rel_booking/rel_book'

  get 'rel_booking/rel_book0'

  get 'rel_booking/rel_book2'

  get 'rel_booking/rel_book3'



  resources :orders
  devise_for :admins
  devise_for :members
  get 'home/index'

  get 'inicio' => 'home#index'

  root 'home#index'

  get 'relatorio' => 'rel_customer#rel_cust'

  resources :items
  resources :companions
  resources :bookings
  resources :cars
  resources :customers
  resources :situations
  resources :reasons
  resources :products
  resources :federations
  resources :employees
  resources :graduations
  resources :forces
  resources :apartments



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/apartment.rb
class Apartment < ApplicationRecord
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :apartment
  belongs_to :graduation
  belongs_to :employee
  belongs_to :reason
  belongs_to :order

  belongs_to :force
  belongs_to :situation


  
  has_many :companions

  validates :dt_entrada, presence: true
  validates :dt_saida, presence: true
  validates :dt_reserva, presence: true
  validates :dt_pgto, presence: true
 

  has_one :customer
  accepts_nested_attributes_for :customer
  accepts_nested_attributes_for :force
  accepts_nested_attributes_for :situation 
  accepts_nested_attributes_for :companions, reject_if: :all_blank, allow_destroy: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :customer
end

app/models/companion.rb
class Companion < ApplicationRecord
  belongs_to :booking
end

app/models/customer.rb
class Customer < ApplicationRecord
  #belongs_to :force
  #belongs_to :situation

  belongs_to :booking

  validates :dt_cadastro, presence: true

  has_many :cars
  accepts_nested_attributes_for :cars, reject_if: :all_blank, allow_destroy: true
  
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :service
  belongs_to :product
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/federation.rb
class Federation < ApplicationRecord
end

app/models/force.rb
class Force < ApplicationRecord
	 has_many :customers
end

app/models/graduation.rb
class Graduation < ApplicationRecord
	has_many :bookings
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :order
  belongs_to :product
  #has_many :product


  accepts_nested_attributes_for :product, reject_if: :all_blank, allow_destroy: true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
	#belongs_to :booking
	has_many :items
	has_many :products, through: :items 

	
	accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true

end

app/models/product.rb
class Product < ApplicationRecord
	has_many :items
	has_many :details
	has_many :orders, through: :items 

end

app/models/reason.rb
class Reason < ApplicationRecord
	has_many :bookings
end

app/models/service.rb
class Service < ApplicationRecord
	has_many :details
	##has_many :products, through: :items 

	accepts_nested_attributes_for :details, reject_if: :all_blank, allow_destroy: true

end
 

app/models/situation.rb
class Situation < ApplicationRecord
	has_many :customers
end

app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
  before_action :set_reason, only: [:show, :edit, :update, :destroy]

  # filtro devise 
  # before_action :authenticate_member!
   before_action :authenticate_admin!
   #######

  # GET /reasons
  # GET /reasons.json
  def index
    @reasons = Reason.all
  end

  # GET /reasons/1
  # GET /reasons/1.json
  def show
  end

  # GET /reasons/new
  def new
    @reason = Reason.new
  end

  # GET /reasons/1/edit
  def edit
  end

  # POST /reasons
  # POST /reasons.json
  def create
    @reason = Reason.new(reason_params)

    respond_to do |format|
      if @reason.save
        format.html { redirect_to @reason, notice: 'Reason was successfully created.' }
        format.json { render :show, status: :created, location: @reason }
      else
        format.html { render :new }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reasons/1
  # PATCH/PUT /reasons/1.json
  def update
    respond_to do |format|
      if @reason.update(reason_params)
        format.html { redirect_to @reason, notice: 'Reason was successfully updated.' }
        format.json { render :show, status: :ok, location: @reason }
      else
        format.html { render :edit }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reasons/1
  # DELETE /reasons/1.json
  def destroy
    @reason.destroy
    respond_to do |format|
      format.html { redirect_to reasons_url, notice: 'Reason was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reason
      @reason = Reason.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reason_params
      params.require(:reason).permit(:motivo)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/views/reasons/_form.html.erb
<%= form_with(model: reason, local: true) do |form| %>
  <% if reason.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reason.errors.count, "error") %> prohibited this reason from being saved:</h2>

      <ul>
      <% reason.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :motivo %>
    <%= form.text_field :motivo, id: :reason_motivo %>
  </div>
<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reasons/edit.html.erb
<h1>.:. Editando Motivo .:.</h1>
<br>

<%= render 'form', reason: @reason %>

<br>
<%= link_to 'Mostrar', @reason %> |
<%= link_to 'Voltar', reasons_path %>

app/views/reasons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>.:. Motivos .:.</h1>
<br>

<table>
  <thead>
    <tr>
      <th>Motivo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reasons.each do |reason| %>
      <tr>
        <td><%= reason.motivo %></td>
        <td><%= link_to 'Mostrar', reason %></td>
        <td><%= link_to 'Editar', edit_reason_path(reason) %></td>
        <td><%= link_to 'Excluir', reason, method: :delete, data: { confirm: 'Tem certeza ??' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Motivo', new_reason_path %>

<br/>
<%= link_to "HOME", "/home/index"%>
<br/>

app/views/reasons/new.html.erb
<h1>.:. Novo Motivo .:.</h1>
<br>

<%= render 'form', reason: @reason %>

<br>
<%= link_to 'Voltar', reasons_path %>

app/views/reasons/show.html.erb
<p id="notice"><%= notice %></p>
<h1>.:. Mostrar Motivo .:. </h1>
<br>

<p>
  <strong>Motivo:</strong>
  <%= @reason.motivo %>
</p>

<br>
<%= link_to 'Editar', edit_reason_path(@reason) %> |
<%= link_to 'Voltar', reasons_path %>