config/routes.rb
Rails.application.routes.draw do

  get 'rel_booking/rel_book'

  resources :details
  resources :services


  get 'rel_customer/rel_cust'

  get 'rel_booking/rel_book'

  get 'rel_booking/rel_book0'

  get 'rel_booking/rel_book2'

  get 'rel_booking/rel_book3'



  resources :orders
  devise_for :admins
  devise_for :members
  get 'home/index'

  get 'inicio' => 'home#index'

  root 'home#index'

  get 'relatorio' => 'rel_customer#rel_cust'

  resources :items
  resources :companions
  resources :bookings
  resources :cars
  resources :customers
  resources :situations
  resources :reasons
  resources :products
  resources :federations
  resources :employees
  resources :graduations
  resources :forces
  resources :apartments



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/apartment.rb
class Apartment < ApplicationRecord
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :apartment
  belongs_to :graduation
  belongs_to :employee
  belongs_to :reason
  belongs_to :order

  belongs_to :force
  belongs_to :situation


  
  has_many :companions

  validates :dt_entrada, presence: true
  validates :dt_saida, presence: true
  validates :dt_reserva, presence: true
  validates :dt_pgto, presence: true
 

  has_one :customer
  accepts_nested_attributes_for :customer
  accepts_nested_attributes_for :force
  accepts_nested_attributes_for :situation 
  accepts_nested_attributes_for :companions, reject_if: :all_blank, allow_destroy: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :customer
end

app/models/companion.rb
class Companion < ApplicationRecord
  belongs_to :booking
end

app/models/customer.rb
class Customer < ApplicationRecord
  #belongs_to :force
  #belongs_to :situation

  belongs_to :booking

  validates :dt_cadastro, presence: true

  has_many :cars
  accepts_nested_attributes_for :cars, reject_if: :all_blank, allow_destroy: true
  
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :service
  belongs_to :product
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/federation.rb
class Federation < ApplicationRecord
end

app/models/force.rb
class Force < ApplicationRecord
	 has_many :customers
end

app/models/graduation.rb
class Graduation < ApplicationRecord
	has_many :bookings
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :order
  belongs_to :product
  #has_many :product


  accepts_nested_attributes_for :product, reject_if: :all_blank, allow_destroy: true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
	#belongs_to :booking
	has_many :items
	has_many :products, through: :items 

	
	accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true

end

app/models/product.rb
class Product < ApplicationRecord
	has_many :items
	has_many :details
	has_many :orders, through: :items 

end

app/models/reason.rb
class Reason < ApplicationRecord
	has_many :bookings
end

app/models/service.rb
class Service < ApplicationRecord
	has_many :details
	##has_many :products, through: :items 

	accepts_nested_attributes_for :details, reject_if: :all_blank, allow_destroy: true

end
 

app/models/situation.rb
class Situation < ApplicationRecord
	has_many :customers
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	require "time"
  	require "date"
  	##require "Datetime"

    @dia = Time.now
    @dia1 = Date.today
    @dia2 = DateTime.now

  	@meuNome = 'Aluisio'
  	@email = 'alfit@oi'
  	
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/home/index.html.erb
<div class="jumbotron" align="center">

	<h4 class="display-4">Hotel de Trânsito dos Oficiais</h4>
	<!--<h2>Hotel de Trânsito dos Oficiais</h2>-->
	
		<%= " Hoje: " %><%= l(@dia1) %> 

<% if admin_signed_in? %>
	 <p> <%=  current_admin.email %> (Usuário admin logado)
	 	<%= link_to "  Sair (fechar sessão)", destroy_admin_session_path, method: :delete %>
	 </p>
<% else %>
	  <!--<%= link_to "Cadastro de novo Admin  ", new_admin_registration_path %>§§§§-->
        <%= link_to "  Logar (Entrar Sistema Admin)", new_admin_session_path %>
<% end %>
   
<% if member_signed_in? %>
	 <p> <%=  current_member.email %> (Usuário membro logado)
	 	<%= link_to "  Sair (fechar sessão)", destroy_member_session_path, method: :delete %>
	 </p>
<% else %>
	  <!--<%= link_to "Cadastro de novo Membro  ", new_member_registration_path %>§§§§-->
        <%= link_to "  Logar (Entrar Sistema Membro)", new_member_session_path %>

<% end %>
	
</div>

<!--<ul>-->
	<br/>
	
	<table>
		
		<tr>
			<td><%= "....."%><%= link_to t('buttons.Pes_Res_Simples'), rel_booking_rel_book0_path, class: "btn btn-primary" %> <%= "....."%>
     		</td> 
		    <td><%= link_to t('buttons.Pes_Res_EeOU'), rel_booking_rel_book2_path, class: "btn btn-primary" %> <%= "....."%>
		    </td>
    		<td><%= link_to t('buttons.Pes_Res_Completa'), rel_booking_rel_book3_path, class: "btn btn-primary" %> <%= "....."%>
		    </td> 
		    <td> <%= link_to t('buttons.Rel_Reservas'), bookings_path, class: "btn btn-primary" %>
     		</td>
	    </tr>
		
	</table>
   
     <!--<li><%= link_to "Reservas", "/bookings"%></li>-->
		
     <br>
	<table>
		
		<tr>
			<td><%= "....."%> <%= link_to t('buttons.Clientes'), customers_path, class: "btn btn-primary" %></td> 
		    <td><%= "....."%><%= link_to t('buttons.Rel_Clientes'), rel_customer_rel_cust_path, class: "btn btn-primary" %></td>
    		
	    </tr>
		
	</table>
			
 
	<br/>
		<!--<li><%= link_to "Produtos", "/products"%></li>-->
		<%= "....."%><%= link_to t('buttons.Produtos'), products_path, class: "btn btn-primary" %> 
	<br/>
	<br/>

<%= render partial: "/home/p_compartilhada/rodape" %>

app/views/home/p_compartilhada/_rodape.html.erb
<strong>  Seja bem-vindo !! </strong>

<!--<%= @meuNome %><%= "----" %><%= @email %>-->