config/routes.rb
Rails.application.routes.draw do

  get 'rel_booking/rel_book'

  resources :details
  resources :services


  get 'rel_customer/rel_cust'

  get 'rel_booking/rel_book'

  get 'rel_booking/rel_book0'

  get 'rel_booking/rel_book2'

  get 'rel_booking/rel_book3'



  resources :orders
  devise_for :admins
  devise_for :members
  get 'home/index'

  get 'inicio' => 'home#index'

  root 'home#index'

  get 'relatorio' => 'rel_customer#rel_cust'

  resources :items
  resources :companions
  resources :bookings
  resources :cars
  resources :customers
  resources :situations
  resources :reasons
  resources :products
  resources :federations
  resources :employees
  resources :graduations
  resources :forces
  resources :apartments



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/apartment.rb
class Apartment < ApplicationRecord
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :apartment
  belongs_to :graduation
  belongs_to :employee
  belongs_to :reason
  belongs_to :order

  belongs_to :force
  belongs_to :situation


  
  has_many :companions

  validates :dt_entrada, presence: true
  validates :dt_saida, presence: true
  validates :dt_reserva, presence: true
  validates :dt_pgto, presence: true
 

  has_one :customer
  accepts_nested_attributes_for :customer
  accepts_nested_attributes_for :force
  accepts_nested_attributes_for :situation 
  accepts_nested_attributes_for :companions, reject_if: :all_blank, allow_destroy: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :customer
end

app/models/companion.rb
class Companion < ApplicationRecord
  belongs_to :booking
end

app/models/customer.rb
class Customer < ApplicationRecord
  #belongs_to :force
  #belongs_to :situation

  belongs_to :booking

  validates :dt_cadastro, presence: true

  has_many :cars
  accepts_nested_attributes_for :cars, reject_if: :all_blank, allow_destroy: true
  
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :service
  belongs_to :product
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/federation.rb
class Federation < ApplicationRecord
end

app/models/force.rb
class Force < ApplicationRecord
	 has_many :customers
end

app/models/graduation.rb
class Graduation < ApplicationRecord
	has_many :bookings
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :order
  belongs_to :product
  #has_many :product


  accepts_nested_attributes_for :product, reject_if: :all_blank, allow_destroy: true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
	#belongs_to :booking
	has_many :items
	has_many :products, through: :items 

	
	accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true

end

app/models/product.rb
class Product < ApplicationRecord
	has_many :items
	has_many :details
	has_many :orders, through: :items 

end

app/models/reason.rb
class Reason < ApplicationRecord
	has_many :bookings
end

app/models/service.rb
class Service < ApplicationRecord
	has_many :details
	##has_many :products, through: :items 

	accepts_nested_attributes_for :details, reject_if: :all_blank, allow_destroy: true

end
 

app/models/situation.rb
class Situation < ApplicationRecord
	has_many :customers
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # filtro devise 
  # before_action :authenticate_member!
   before_action :authenticate_admin!

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:nr, :descricao, :leito, :status, :observacao)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/apartments/_form.html.erb
<%= form_with(model: apartment, local: true) do |form| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nr %>
    <%= form.number_field :nr, id: :apartment_nr %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao, id: :apartment_descricao %>
  </div>

  <div class="field">
    <%= form.label :leito %>
    <%= form.text_field :leito, id: :apartment_leito %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :apartment_status %>
  </div>

  <div class="field">
    <%= form.label :observacao %>
    <%= form.text_field :observacao, id: :apartment_observacao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>.:. Editando Apartamento .:.</h1>
<br>

<%= render 'form', apartment: @apartment %>

<br>
<%= link_to 'Mostrar', @apartment %> |
<%= link_to 'Voltar', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>
<h1>.:. Apartamentos .:.</h1>
<br>

<table>
  <thead>
    <tr>
      <th>Nr</th>
      <th>Descricao</th>
      <th>Leito</th>
      <th>Status</th>
      <th>Observacao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.nr %></td>
        <td><%= apartment.descricao %></td>
        <td><%= apartment.leito %></td>
        <td><%= apartment.status %></td>
        <td><%= apartment.observacao %></td>
        <td><%= link_to 'Mostrar', apartment %></td>
        <td><%= link_to 'Editar', edit_apartment_path(apartment) %></td>
        <td><%= link_to 'Excluir', apartment, method: :delete, data: { confirm: 'Tem certeza ??' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Apartamento', new_apartment_path %>

<br/>
<%= link_to "HOME", "/home/index"%>
<br/>

app/views/apartments/new.html.erb
<h1>.:. Novo Apartamento .:.</h1>
<br>

<%= render 'form', apartment: @apartment %>

<br>
<%= link_to 'Voltar', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>
<h1>.:. Mostrar Apartamento .:. </h1>
<br>

<p>
  <strong>Nr:</strong>
  <%= @apartment.nr %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @apartment.descricao %>
</p>

<p>
  <strong>Leito:</strong>
  <%= @apartment.leito %>
</p>

<p>
  <strong>Status:</strong>
  <%= @apartment.status %>
</p>

<p>
  <strong>Observacao:</strong>
  <%= @apartment.observacao %>
</p>

<br>
<%= link_to 'Editar', edit_apartment_path(@apartment) %> |
<%= link_to 'Voltar', apartments_path %>